replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-spring-jkube-jenkins-min/hello@sha256:551f6426fab5d86597fc89b15f8e5cbb55f6266d939dd5d6838486f8ed4fb736 # written by ploigos-step-runner
