replicaCount: 1
image:
  tag: registry-internal-nexus.apps.tssc.rht-set.com/ploigos-ref/ref-spring-jkube-jenkins-min/hello@sha256:29254f8b30eeb2775b43bfe0f448acb632769285bf4d43f3cc29e7f274a7cdae # written by ploigos-step-runner
